source 'https://rubygems.org'

gem 'sinatra', :github => 'sinatra/sinatra'
gem 'sinatra-contrib'
gem 'dotenv'
gem 'pry-byebug'

# Add your github development branch here
gem 'get_address', :git => 'git@github.com:finn-francis/get_address.git'
